# Default values for trust-tunnel-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: trust-tunnel-agent
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""


securityContext: {}

resources:
  requests:
    cpu: "0"
    memory: 0Gi
  limits:
    cpu: "2"
    memory: 4Gi

nodeSelector: {}

tolerations: []

affinity: {}
